// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxqv5gnOsGvVTq_kvRs5UQNyPDidPaiWM',
    appId: '1:531885296634:web:9f948ebba9a590d5d13243',
    messagingSenderId: '531885296634',
    projectId: 'ecommerce-project-107f4',
    authDomain: 'ecommerce-project-107f4.firebaseapp.com',
    databaseURL: 'https://ecommerce-project-107f4-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-project-107f4.appspot.com',
    measurementId: 'G-9SZE011Q54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBniB15-u2d8FTfOa5ZiXVJSkeQub7Gj-o',
    appId: '1:531885296634:android:f6bf1eb5d3c0721dd13243',
    messagingSenderId: '531885296634',
    projectId: 'ecommerce-project-107f4',
    databaseURL: 'https://ecommerce-project-107f4-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-project-107f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUhM8r_bOT3Mb9JpVdj2w211_esrBnLFQ',
    appId: '1:531885296634:ios:84b0a93eb88d2906d13243',
    messagingSenderId: '531885296634',
    projectId: 'ecommerce-project-107f4',
    databaseURL: 'https://ecommerce-project-107f4-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-project-107f4.appspot.com',
    androidClientId: '531885296634-arrvuvj2ru5n2va63dqmlr62oaga797r.apps.googleusercontent.com',
    iosClientId: '531885296634-b1696o03hb54n1bk6n859574q996b8u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketky',
  );
}
